language: go

# Setting sudo access to false will let Travis CI use containers rather than
# VMs to run the tests. For more details see:
# - http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# - http://docs.travis-ci.com/user/workers/standard-infrastructure/
sudo: false

install: make bootstrap
script: GOPATH=${PWD}/_vendor go test -v ./...

notifications:
  irc: "irc.freenode.net#masterminds"